version: "3.8"

services:
    db:
        image: postgres:15
        container_name: task-manager-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: task_manager

        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
        driver: local
